/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imu_data implements lcm.lcm.LCMEncodable
{
    public float linearAcc[];
    public float angularVel[];
    public float rpy[];
    public float quat[];
 
    public imu_data()
    {
        linearAcc = new float[3];
        angularVel = new float[3];
        rpy = new float[3];
        quat = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x201098a6cc5cf89aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.imu_data.class))
            return 0L;
 
        classes.add(lcmtypes.imu_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.linearAcc[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.angularVel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quat[a]); 
        }
 
    }
 
    public imu_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imu_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.imu_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.imu_data o = new lcmtypes.imu_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.linearAcc = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.linearAcc[a] = ins.readFloat();
        }
 
        this.angularVel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.angularVel[a] = ins.readFloat();
        }
 
        this.rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy[a] = ins.readFloat();
        }
 
        this.quat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.imu_data copy()
    {
        lcmtypes.imu_data outobj = new lcmtypes.imu_data();
        outobj.linearAcc = new float[(int) 3];
        System.arraycopy(this.linearAcc, 0, outobj.linearAcc, 0, 3); 
        outobj.angularVel = new float[(int) 3];
        System.arraycopy(this.angularVel, 0, outobj.angularVel, 0, 3); 
        outobj.rpy = new float[(int) 3];
        System.arraycopy(this.rpy, 0, outobj.rpy, 0, 3); 
        outobj.quat = new float[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        return outobj;
    }
 
}

