/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_data implements lcm.lcm.LCMEncodable
{
    public double q[];
    public double v[];
    public double tau[];
 
    public motor_data()
    {
        q = new double[12];
        v = new double[12];
        tau = new double[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4950d578b08d9279L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motor_data.class))
            return 0L;
 
        classes.add(lcmtypes.motor_data.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.q[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.v[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.tau[a]); 
        }
 
    }
 
    public motor_data(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_data(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motor_data _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motor_data o = new lcmtypes.motor_data();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q[a] = ins.readDouble();
        }
 
        this.v = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.v[a] = ins.readDouble();
        }
 
        this.tau = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tau[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.motor_data copy()
    {
        lcmtypes.motor_data outobj = new lcmtypes.motor_data();
        outobj.q = new double[(int) 12];
        System.arraycopy(this.q, 0, outobj.q, 0, 12); 
        outobj.v = new double[(int) 12];
        System.arraycopy(this.v, 0, outobj.v, 0, 12); 
        outobj.tau = new double[(int) 12];
        System.arraycopy(this.tau, 0, outobj.tau, 0, 12); 
        return outobj;
    }
 
}

