/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_command implements lcm.lcm.LCMEncodable
{
    public double qDes[];
    public double vDes[];
    public double tauff[];
    public double Kp[];
    public double Kd[];
 
    public motor_command()
    {
        qDes = new double[12];
        vDes = new double[12];
        tauff = new double[12];
        Kp = new double[12];
        Kd = new double[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x50ae477344d1fb92L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.motor_command.class))
            return 0L;
 
        classes.add(lcmtypes.motor_command.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.qDes[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.vDes[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.tauff[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.Kp[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeDouble(this.Kd[a]); 
        }
 
    }
 
    public motor_command(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_command(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.motor_command _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.motor_command o = new lcmtypes.motor_command();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.qDes = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qDes[a] = ins.readDouble();
        }
 
        this.vDes = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.vDes[a] = ins.readDouble();
        }
 
        this.tauff = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tauff[a] = ins.readDouble();
        }
 
        this.Kp = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.Kp[a] = ins.readDouble();
        }
 
        this.Kd = new double[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.Kd[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.motor_command copy()
    {
        lcmtypes.motor_command outobj = new lcmtypes.motor_command();
        outobj.qDes = new double[(int) 12];
        System.arraycopy(this.qDes, 0, outobj.qDes, 0, 12); 
        outobj.vDes = new double[(int) 12];
        System.arraycopy(this.vDes, 0, outobj.vDes, 0, 12); 
        outobj.tauff = new double[(int) 12];
        System.arraycopy(this.tauff, 0, outobj.tauff, 0, 12); 
        outobj.Kp = new double[(int) 12];
        System.arraycopy(this.Kp, 0, outobj.Kp, 0, 12); 
        outobj.Kd = new double[(int) 12];
        System.arraycopy(this.Kd, 0, outobj.Kd, 0, 12); 
        return outobj;
    }
 
}

