"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class imu_data(object):
    __slots__ = ["linearAcc", "angularVel", "rpy", "quat"]

    def __init__(self):
        self.linearAcc = [ 0.0 for dim0 in range(3) ]
        self.angularVel = [ 0.0 for dim0 in range(3) ]
        self.rpy = [ 0.0 for dim0 in range(3) ]
        self.quat = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(imu_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.linearAcc[:3]))
        buf.write(struct.pack('>3f', *self.angularVel[:3]))
        buf.write(struct.pack('>3f', *self.rpy[:3]))
        buf.write(struct.pack('>4f', *self.quat[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imu_data()
        self.linearAcc = struct.unpack('>3f', buf.read(12))
        self.angularVel = struct.unpack('>3f', buf.read(12))
        self.rpy = struct.unpack('>3f', buf.read(12))
        self.quat = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imu_data in parents: return 0
        tmphash = (0x201098a6cc5cf89a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imu_data._packed_fingerprint is None:
            imu_data._packed_fingerprint = struct.pack(">Q", imu_data._get_hash_recursive([]))
        return imu_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

