"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motor_data(object):
    __slots__ = ["q", "v", "tau"]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(12) ]
        self.v = [ 0.0 for dim0 in range(12) ]
        self.tau = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(motor_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.q[:12]))
        buf.write(struct.pack('>12d', *self.v[:12]))
        buf.write(struct.pack('>12d', *self.tau[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_data._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_data()
        self.q = struct.unpack('>12d', buf.read(96))
        self.v = struct.unpack('>12d', buf.read(96))
        self.tau = struct.unpack('>12d', buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motor_data in parents: return 0
        tmphash = (0x4950d578b08d9279) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_data._packed_fingerprint is None:
            motor_data._packed_fingerprint = struct.pack(">Q", motor_data._get_hash_recursive([]))
        return motor_data._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

