"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class motor_command(object):
    __slots__ = ["qDes", "vDes", "tauff", "Kp", "Kd"]

    def __init__(self):
        self.qDes = [ 0.0 for dim0 in range(12) ]
        self.vDes = [ 0.0 for dim0 in range(12) ]
        self.tauff = [ 0.0 for dim0 in range(12) ]
        self.Kp = [ 0.0 for dim0 in range(12) ]
        self.Kd = [ 0.0 for dim0 in range(12) ]

    def encode(self):
        buf = BytesIO()
        buf.write(motor_command._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12d', *self.qDes[:12]))
        buf.write(struct.pack('>12d', *self.vDes[:12]))
        buf.write(struct.pack('>12d', *self.tauff[:12]))
        buf.write(struct.pack('>12d', *self.Kp[:12]))
        buf.write(struct.pack('>12d', *self.Kd[:12]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != motor_command._get_packed_fingerprint():
            raise ValueError("Decode error")
        return motor_command._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = motor_command()
        self.qDes = struct.unpack('>12d', buf.read(96))
        self.vDes = struct.unpack('>12d', buf.read(96))
        self.tauff = struct.unpack('>12d', buf.read(96))
        self.Kp = struct.unpack('>12d', buf.read(96))
        self.Kd = struct.unpack('>12d', buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if motor_command in parents: return 0
        tmphash = (0x50ae477344d1fb92) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if motor_command._packed_fingerprint is None:
            motor_command._packed_fingerprint = struct.pack(">Q", motor_command._get_hash_recursive([]))
        return motor_command._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

